brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy


urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
    TodoItemCreateView,
    TodoListView,
    TodoListDetailView,
    TodoListCreateView,
    TodoListUpdateView,
    TodoListDeleteView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="list_todos"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="show_todolist"),
    path("create/", TodoListCreateView.as_view(), name="create_todolist"),
    path("<int:pk>/edit", TodoListUpdateView.as_view(), name="update_todolist"),
    path(
        "<int:pk>/delete", TodoListDeleteView.as_view(), name="delete_todolist"
    ),
    path("items/create", TodoItemCreateView.as_view(), name="create_todoitem"),
]

todos/models.py
from xmlrpc.client import boolean
from django.db import models
from django.forms import CharField

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/forms.py
from django.forms import ModelForm
from todos.models import TodoItem, TodoList


class TodoListForm(ModelForm):
    class Meta:
        model = TodoList
        fields = "__all__"


class TodoItemForm(ModelForm):
    class Meta:
        model = TodoItem
        fields = "__all__"

todos/views.py
from unicodedata import name
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from tests import todo_lists
from todos.models import TodoList, TodoItem
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect

# Create your views here.


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"

    def get_context_data(self, **kwargs):
        context = super(TodoListView, self).get_context_data(**kwargs)
        return context


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoListCreateView(CreateView):
    model = TodoList
    template_name = "todos/new.html"
    fields = ["name"]
    success_url = reverse_lazy("list_todos")


class TodoListUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]

    def get_success_url(self):
        todopk = self.kwargs["pk"]
        return reverse_lazy("show_todolist", kwargs={"pk": todopk})


class TodoListDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("list_todos")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todos/items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]
    success_url = reverse_lazy("list_todos")

todos/templates/todos/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="post">
                {% csrf_token %}
                {{form.as.p}}
                <button type="submit">Delete</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/detail.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        
        <div>
            <h1>{{todolist.name}}</h1>
            <a href="{% url 'update_todolist' todolist.pk%}">Edit</a> <br>
            <a href="{% url 'delete_todolist' todolist.pk%}">Delete</a>
            <h2>Tasks:</h2>
            
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in todolist.items.all %}
                        <tr>
                            <td colspan="2"> <a href="{% url 'show_todolist' task.pk%}">{{task.task}}</a> </td> 
                            <td> {{ task.due_date}} </td>
                        </tr>
                    {% endfor %}
                </tbody>                     
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Update List</h1>
            <form method="post">
                {% csrf_token %}
                {{form.as.p}}
                <label for="name">Name:</label>
                <input type="text" id="name" name="name"><br>
                <button type="submit">Update</button>
            </form>                
        </div>
    </main>
</body>
</html>

todos/templates/todos/items/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <main>
        <div>
            <h1>Create new item</h1>
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                
                <button>Create</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/list.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Lists</title>
</head>
<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <p><a href="{% url 'create_todolist' %}">Create a new list</a></p>
            <p><a href="{% url 'create_todoitem' %}">Create a new item</a></p>
            
            <table>
                                <thead>
                    <tr>
                        <th colspan="2">Name</th>
                        <th>Number of Items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in todolist_list.all %}
                        <tr>
                            <td> <a href="{% url 'show_todolist' item.pk%}">{{item.name}}</a></td> 
                            <td> {{ item.items.all|length}} </td>
                        </tr>
                    {% endfor %}
                </tbody>                     
            </table>     
        </div>
    </main>
</body>
</html>

todos/templates/todos/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Todo List</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new list:</h1>
            <form method = "post">
                {% csrf_token %}
                {{form.as.p}}
            <div>
                <label for="name">Name:</label>
                <input type="text" id="name" name="name"><br>
                <button type="submit">Create</button>
            </div>
        </div>
        </form>
    </main>
</body>
</html>